/**
 * ZNPList<T> — Generic singly-linked list backed by ZNPNode<T>.
 *
 * Replaces 35 identical ZNPList_* classes previously generated by
 * createZNPList() factory in nape-compiled.js.
 *
 * Each concrete subclass must set a static `_NodeClass` property pointing
 * to the corresponding ZNPNode subclass for pool allocation.
 */
import { ZNPNode } from "./ZNPNode";

interface ZNPNodeClass<T> {
  new (): ZNPNode<T>;
  zpp_pool: ZNPNode<T> | null;
}

interface ZNPListConstructor<T> {
  _NodeClass: ZNPNodeClass<T>;
}

export class ZNPList<T> {
  static _NodeClass: ZNPNodeClass<unknown>;

  head: ZNPNode<T> | null = null;
  length: number = 0;
  modified: boolean = false;
  pushmod: boolean = false;

  // Node class cached per instance so the pool fast path is a monomorphic
  // field load instead of a megamorphic this.constructor lookup.
  private readonly _N: ZNPNodeClass<T> = (this.constructor as unknown as ZNPListConstructor<T>)
    ._NodeClass;

  private _allocNode(): ZNPNode<T> {
    const N = this._N;
    let ret: ZNPNode<T>;
    if (N.zpp_pool == null) {
      ret = new N();
    } else {
      ret = N.zpp_pool;
      N.zpp_pool = ret.next;
      ret.next = null;
    }
    return ret;
  }

  private _freeNode(node: ZNPNode<T>): void {
    const N = this._N;
    node.elt = null;
    node.next = N.zpp_pool;
    N.zpp_pool = node;
  }

  begin(): ZNPNode<T> | null {
    return this.head;
  }

  add(o: T): T {
    const node = this._allocNode();
    node.elt = o;
    node.next = this.head;
    this.head = node;
    this.modified = true;
    this.length++;
    return o;
  }

  insert(cur: ZNPNode<T> | null, o: T): ZNPNode<T> {
    const node = this._allocNode();
    node.elt = o;
    if (cur == null) {
      node.next = this.head;
      this.head = node;
    } else {
      node.next = cur.next;
      cur.next = node;
    }
    this.pushmod = this.modified = true;
    this.length++;
    return node;
  }

  pop(): void {
    const ret = this.head!;
    this.head = ret.next;
    this._freeNode(ret);
    if (this.head == null) {
      this.pushmod = true;
    }
    this.modified = true;
    this.length--;
  }

  pop_unsafe(): T {
    const ret = this.head!.elt!;
    this.pop();
    return ret;
  }

  erase(pre: ZNPNode<T> | null): ZNPNode<T> | null {
    let old: ZNPNode<T>;
    let ret: ZNPNode<T> | null;
    if (pre == null) {
      old = this.head!;
      ret = old.next;
      this.head = ret;
      if (this.head == null) {
        this.pushmod = true;
      }
    } else {
      old = pre.next!;
      ret = old.next;
      pre.next = ret;
      if (ret == null) {
        this.pushmod = true;
      }
    }
    this._freeNode(old);
    this.modified = true;
    this.length--;
    this.pushmod = true;
    return ret;
  }

  remove(obj: T): void {
    let pre: ZNPNode<T> | null = null;
    let cur = this.head;
    while (cur != null) {
      if (cur.elt == obj) {
        this.erase(pre);
        break;
      }
      pre = cur;
      cur = cur.next;
    }
  }

  clear(): void {
    while (this.head != null) {
      const ret = this.head;
      this.head = ret.next;
      this._freeNode(ret);
      if (this.head == null) {
        this.pushmod = true;
      }
      this.modified = true;
      this.length--;
    }
    this.pushmod = true;
  }

  reverse(): void {
    let cur = this.head;
    let pre: ZNPNode<T> | null = null;
    while (cur != null) {
      const nx = cur.next;
      cur.next = pre;
      this.head = cur;
      pre = cur;
      cur = nx;
    }
    this.modified = true;
    this.pushmod = true;
  }

  empty(): boolean {
    return this.head == null;
  }

  has(obj: T): boolean {
    let cx_ite = this.head;
    while (cx_ite != null) {
      if (cx_ite.elt == obj) return true;
      cx_ite = cx_ite.next;
    }
    return false;
  }

  iterator_at(ind: number): ZNPNode<T> | null {
    let ret = this.head;
    while (ind-- > 0 && ret != null) ret = ret.next;
    return ret;
  }

  at(ind: number): T | null {
    const it = this.iterator_at(ind);
    return it != null ? it.elt : null;
  }
}
