/**
 * Core engine module — manages access to the compiled nape namespace.
 *
 * The nape-compiled.js file is generated by the prebuild script from the
 * original AMD module.  It evaluates synchronously on import, so the
 * namespace is available immediately.
 */

import napeNamespace from "./nape-compiled.js";

/**
 * Returns the internal nape namespace object.
 *
 * All wrapper classes use this to access the underlying Haxe-compiled
 * constructors and prototypes.
 *
 * @internal
 */
export function getNape(): any {
  if (!napeNamespace) {
    throw new Error(
      "Nape physics engine failed to initialize. " +
        "Make sure the package was built correctly (npm run build).",
    );
  }
  return napeNamespace;
}
