/**
 * Core engine module — manages access to the compiled nape namespace.
 *
 * The nape-compiled.js file is generated by the prebuild script from the
 * original AMD module.  It evaluates synchronously on import, so the
 * namespace is available immediately.
 */

import napeNamespace from "./nape-compiled.js";

/**
 * Returns the internal nape namespace object.
 *
 * All wrapper classes use this to access the underlying Haxe-compiled
 * constructors and prototypes.
 *
 * @internal
 */
export function getNape(): any {
  if (!napeNamespace) {
    throw new Error(
      "Nape physics engine failed to initialize. " +
        "Make sure the package was built correctly (npm run build).",
    );
  }
  return napeNamespace;
}

// Config constants — must run before any physics simulation.
import "../Config";

// Debug utility class.
import "../util/Debug";

// Register typed List + Iterator classes after the compiled code is loaded.
// This must happen here (not just in index.ts) so that any module importing
// getNape() — even without going through the barrel export — gets the lists.
import "../util/registerLists";

// Internal list backing classes — must run after registerLists so the public
// wrapper classes (BodyList, ConstraintList, etc.) are already in nape namespace.
import "../native/util/ZPP_PublicList";

// Special-case lists (Vec2List, ContactList, GeomVertexIterator) that have
// custom behavior not handled by the generic NapeListFactory.
// Public classes must register before ZPP classes reference them.
import "../geom/Vec2List";
import "../dynamics/ContactList";
import "../geom/GeomVertexIterator";
import "../native/util/ZPP_Vec2List";
import "../native/util/ZPP_ContactList";
import "../native/geom/ZPP_GeomVertexIterator";
import "../native/util/ZPP_MixVec2List";

// Singleton enum classes — import so they self-register before user code runs.
// Each class calls ensureEnumsReady() after registering; _initEnums runs once
// all 6 classes are available (handles circular-import cycles gracefully).
import "../callbacks/CbEvent";
import "../callbacks/CbType";
import "../callbacks/ListenerType";
import "../dynamics/ArbiterType";
import "../phys/BodyType";
import "../shape/ShapeType";

// Deferred singleton enum initialization — called by each enum class after
// self-registering.  Runs _initEnums only when all 6 constructors exist.
// eslint-disable-next-line no-var
var _enumsReady = false;
export function ensureEnumsReady(): void {
  if (_enumsReady) return;
  const n = napeNamespace;
  if (
    !n?.callbacks?.CbEvent ||
    !n?.callbacks?.CbType ||
    !n?.callbacks?.ListenerType ||
    !n?.dynamics?.ArbiterType ||
    !n?.phys?.BodyType ||
    !n?.shape?.ShapeType
  ) {
    return; // Not all enum classes registered yet — will retry when the last one loads.
  }
  _enumsReady = true;
  const _z = n.__zpp;
  _z.callbacks.ZPP_CbType._initEnums(n);
  _z.callbacks.ZPP_Listener._initEnums(n, _z.util.ZPP_Flags);
  _z.dynamics.ZPP_Arbiter._initEnums(n, _z.util.ZPP_Flags);
  _z.phys.ZPP_Body._initEnums(n, _z.util.ZPP_Flags);
  _z.shape.ZPP_Shape._initEnums(n, _z.util.ZPP_Flags);
}
