/**
 * HaxeShims — TypeScript replacements for Haxe-to-JS runtime shims.
 *
 * Extracted from nape-compiled.js Priority 18.
 * These were originally generated by the Haxe compiler as runtime support.
 */

// ---------------------------------------------------------------------------
// Reflect — Haxe reflection utilities
// ---------------------------------------------------------------------------
export const Reflect: any = function () {};
Reflect.__name__ = ["Reflect"];
Reflect.field = function (o: any, field: string): any {
  try {
    return o[field];
  } catch (_e: any) {
    return null;
  }
};
Reflect.fields = function (o: any): string[] {
  const a: string[] = [];
  if (o != null) {
    const hasOwnProperty = Object.prototype.hasOwnProperty;
    for (const f in o) {
      if (
        f != "__id__" &&
        f != "hx__closures__" &&
        hasOwnProperty.call(o, f)
      ) {
        a.push(f);
      }
    }
  }
  return a;
};
Reflect.copy = function (o: any): any {
  if (o == null) return null;
  const o2: any = {};
  const fields = Reflect.fields(o);
  for (let i = 0; i < fields.length; i++) {
    o2[fields[i]] = Reflect.field(o, fields[i]);
  }
  return o2;
};

// ---------------------------------------------------------------------------
// Std — Haxe standard library shim
// ---------------------------------------------------------------------------
export const Std: any = function () {};
Std.__name__ = ["Std"];
Std.string = function (s: any): string {
  return jsBoot.__string_rec(s, "");
};

// ---------------------------------------------------------------------------
// StringTools — Haxe string utilities
// ---------------------------------------------------------------------------
export const StringTools: any = function () {};
StringTools.__name__ = ["StringTools"];
StringTools.hex = function (n: number, digits?: number): string {
  let s = "";
  const hexChars = "0123456789ABCDEF";
  do {
    s = hexChars.charAt(n & 15) + s;
    n >>>= 4;
  } while (n > 0);
  if (digits != null) {
    while (s.length < digits) s = "0" + s;
  }
  return s;
};

// ---------------------------------------------------------------------------
// js._Boot.HaxeError — Haxe error wrapper
// ---------------------------------------------------------------------------
class HaxeError extends Error {
  val: any;

  constructor(val: any) {
    super();
    this.val = val;
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, HaxeError);
    }
  }
}
(HaxeError as any).__name__ = ["js", "_Boot", "HaxeError"];
(HaxeError as any).__super__ = Error;
(HaxeError as any).prototype.__class__ = HaxeError;

// ---------------------------------------------------------------------------
// js.Boot — Haxe JS boot utilities
// ---------------------------------------------------------------------------
const jsBoot: any = function () {};
jsBoot.__name__ = ["js", "Boot"];
jsBoot.__string_rec = function (o: any, s: string): string {
  if (o == null) return "null";
  if (s.length >= 5) return "<...>";
  const t = typeof o;
  const effectiveType =
    t == "function" && (o.__name__ || o.__ename__) ? "object" : t;
  switch (effectiveType) {
    case "function":
      return "<function>";
    case "object":
      if (o instanceof Array) {
        let str = "[";
        s += "\t";
        for (let i = 0; i < o.length; i++) {
          str += (i > 0 ? "," : "") + jsBoot.__string_rec(o[i], s);
        }
        str += "]";
        return str;
      }
      {
        let tostr: any;
        try {
          tostr = o.toString;
        } catch (_e: any) {
          return "???";
        }
        if (
          tostr != null &&
          tostr != Object.toString &&
          typeof tostr == "function"
        ) {
          const s2 = o.toString();
          if (s2 != "[object Object]") return s2;
        }
        let str1 = "{\n";
        s += "\t";
        const hasp = o.hasOwnProperty != null;
        for (const k in o) {
          if (hasp && !o.hasOwnProperty(k)) continue;
          if (
            k == "prototype" ||
            k == "__class__" ||
            k == "__super__" ||
            k == "__interfaces__" ||
            k == "__properties__"
          )
            continue;
          if (str1.length != 2) str1 += ", \n";
          str1 += s + k + " : " + jsBoot.__string_rec(o[k], s);
        }
        s = s.substring(1);
        str1 += "\n" + s + "}";
        return str1;
      }
    case "string":
      return o;
    default:
      return String(o);
  }
};
jsBoot.__toStr = null as any;

// ---------------------------------------------------------------------------
// Assembled `js` namespace (matches compiled code's `js` variable structure)
// ---------------------------------------------------------------------------
export const js: any = {
  _Boot: { HaxeError },
  Boot: jsBoot,
};

// ---------------------------------------------------------------------------
// $estr / $bind — Haxe runtime helpers (unused but kept for compatibility)
// ---------------------------------------------------------------------------
export function $estr(this: any): string {
  return jsBoot.__string_rec(this, "");
}

export function $bind(o: any, m: any): any {
  const f: any = function (this: any) {
    return f.method.apply(f.scope, arguments);
  };
  f.scope = o;
  f.method = m;
  return f;
}

export { jsBoot, HaxeError };

// ---------------------------------------------------------------------------
// Haxe runtime bootstrap — executed once at module load time.
// Previously in nape-compiled.js; moved here (Priority 20).
// ---------------------------------------------------------------------------
(String as any).__name__ = true;
(Array as any).__name__ = true;
Object.defineProperty(HaxeError.prototype, "message", {
  get: function () {
    return String(this.val);
  },
});
jsBoot.__toStr = ({} as any).toString;
